# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Ferhat Kortak
tagline:	'blog'
description:	'Kişisel Blogum'
url:		http://ferhatkortak.github.io

author:
  name:		'Ferhat Kortak '
  url:		ferhatkortak.wordpress.com

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/ferhatkortak
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/ferhatkortak
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+ferhatkortak
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Ferhat Kortak
  url:		http://ferhatkortak.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
